import { Vector3 } from "three";

export const PLANET_RADIUS = 2.5;
export const LANDMARK_BUILDING_HEIGHT = 1;
export const CHARACTER_SIZE_RATIO = 0.52;
export const CHARACTER_SURFACE_LIFT_RATIO = 0.18;
export const CHARACTER_FORWARD_TILT = -0.18;
export const CHARACTER_BACKWARD_TILT = 0.1;
export const CHARACTER_SIDE_BANK = -0.16;
export const CHARACTER_TILT_SMOOTHING = 8;
export const CHARACTER_MODEL_YAW_OFFSET = Math.PI;
export const CHARACTER_HEIGHT = LANDMARK_BUILDING_HEIGHT * CHARACTER_SIZE_RATIO;
export const CHARACTER_SURFACE_LIFT =
  LANDMARK_BUILDING_HEIGHT * CHARACTER_SURFACE_LIFT_RATIO;
export const CHARACTER_FIXED_POSITION = new Vector3(
  0,
  PLANET_RADIUS + CHARACTER_SURFACE_LIFT + CHARACTER_HEIGHT / 2,
  0,
);
export const CHARACTER_COLLISION_POSITION = new Vector3(
  0,
  PLANET_RADIUS + CHARACTER_SURFACE_LIFT + LANDMARK_BUILDING_HEIGHT * 0.175,
  0,
);